server:
  port: 8762
spring:
  application:
    name: service-config
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
